spring:
  application:
    name: rbjrg-app
#  main:
#    web-application-type: SERVLET
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/rbjrg-app

server:
  port: 8080
  servlet:
    context-path: /rbjrg

#logging:
#  pattern:
#    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
